### ISSUE TITLE
forensic1394_read_device_v: General I/O error        forensic1394_read_device_v: I/O timeout

### ISSUE THREAD

**Issue by SirCosty** [carmaa/inception#106]
I used inception v0.3.5 like 3 months ago and it have worked good with Kali linux.
Now did wanted to try the new Implant but before to get to that point just saw that the Unlock is not working anymore.
I use the same hardware like before and same target but it is not working anymore.
Then I have checkout from git the old v0.3.5 and its still working

root@kali:~# sudo incept unlock

| _| _| _||| _|||| ||| _||| _| _|| | _|
_| _|| | _| _| _| _| _| _| _| _| _|| |
_| _| _| _| _| _||| _||| _| _| _| _| _| _| _|
_| _| _|| | _| _| _| _| _| _| _| _||
| _| _| _||| _|||| | _| _| _|| _| _|

v.0.4.0 (C) Carsten Maartmann-Moe 2014
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

| _| _| _||| _|||| ||| _||| _| _|| | _|
_| _|| | _| _| _| _| _| _| _| _| _|| |
_| _| _| _| _| _||| _||| _| _| _| _| _| _| _|
_| _| _|| | _| _| _| _| _| _| _| _||
| _| _| _||| _|||| | _| _| _|| _| _|

v.0.4.0 (C) Carsten Maartmann-Moe 2014
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID): (0x0)

[] Only one device present, device auto-selected as target
[] Selected device: MICROSOFT CORP.
[/] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[*] Available targets (known signatures):

[1] Windows 8 MsvpPasswordValidate unlock/privilege escalation
[2] Windows 7 MsvpPasswordValidate unlock/privilege escalation
[3] Windows Vista MsvpPasswordValidate unlock/privilege escalation
[4] Windows XP MsvpPasswordValidate unlock/privilege escalation
[5] Mac OS X DirectoryService/OpenDirectory unlock/privilege escalation
[6] Ubuntu libpam unlock/privilege escalation
[7] Linux Mint libpam unlock/privilege escalation

[?] Please select target (or enter 'q' to quit): 4
[*] Selected target: Windows XP MsvpPasswordValidate unlock/privilege escalation
[> ] 0 MiB ( 0%)
[!] Warning: Something went dreadfully wrong, full stack trace below:
forensic1394_read_device_v: General I/O error

Traceback (most recent call last):
File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/EGG-INFO/scripts/incept", line 168, in main
module.run(opts, memspace)
File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/inception/modules/unlock.py", line 599, in run
address, signature, offset = memspace.find(target, verbose=opts.verbose)
File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/inception/memory.py", line 325, in find
for caddr, cand in self.interface.readv(r):
File "/usr/local/lib/python3.2/dist-packages/forensic1394/device.py", line 174, in readv
self._readreq(req, buf)
File "/usr/local/lib/python3.2/dist-packages/forensic1394/device.py", line 134, in _readreq
forensic1394_read_device_v(self, creq, len(creq))
File "/usr/local/lib/python3.2/dist-packages/forensic1394/errors.py", line 61, in process_result
raise IOError(err)
IOError: forensic1394_read_device_v: General I/O error

**Comment by dragosb91** [comment]
Is this issue fixed? On my setup I get the I/O timeout error everytime it reaches 86%. I tried the unlock and dump module. What could be the reason for this?:
sudo incept dump

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter


 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID):  (0x0)

[*] Only one device present, device auto-selected as target
[*] Selected device: MICROSOFT CORP.
[\] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[*] Dumping from 0x0 to 0x100000000, a total of 4 GiB:
[-] Error: forensic1394_read_device_v: I/O timeout MiB ( 86%) {0350705703602c58}

**Comment by carmaa** [comment]
Likely you're reaching a gap in the physical memory space, assuming the target has more than 3 GB of main memory. Could handle the I/O errors better though.

**Comment by ohatalsky** [comment]
I am experiencing the same problem as dragosb91, in that my unlock and dump stops at 73 with the same I/O Timeout error.  Are you referring to the gap between actual physical memory, and available memory?  I know I have exactly 4GB of memory on the target machine, and I am only able to pull 3.1 GB with the dump feature.  Because the unlock feature times out I cannot unlock the target machine.  Advice / tips / clarification on your previous answer would be most appreciated.

**Comment by carmaa** [comment]
Yes, there are gaps in physical address space due to other PCI devices' memory (video cards, etc.) being mapped . Best explanation:

http://resources.infosecinstitute.com/system-address-map-initialization-x86x64-architecture-part-2-pci-express-based-systems/

and particularly this figure:

![image of physical memory map](http://2we26u4fam7n16rz3a44uhbe1bq2.wpengine.netdna-cdn.com/wp-content/uploads/010814_1515_SystemAddre16.png)

also

http://www.brokenthorn.com/Resources/OSDev17.html

If it's an option, insert a 2GB RAM module instead. That's not an option in most real-life scenarios, though.

**Comment by wintermute4316** [comment]
Hello Inception team.  Hey just to pass this along in case it helps, I'm experiencing something very similar to what's described above. I tried running the following:

a. Inception on two different Linux laptops (Lenovo and HP running Ubuntu 14.04 and Kali).  I also tried versions 0.3.5, 0.4.0 and 0.4.1 with same results.
b. Victims I tried both Windows 7 and Windows 8 64 bit target laptops, both running 8GB of RAM
c. All systems had firewire enabled in bios with fully working 4pin firewire ports

I) Unlock Issue: When I try the unlock capability, in all variations given above, the unlock starts, I hear the audio prompt on the victim indicating a firewire device is being added, I'm prompted to choose the type of target (Win 7 or Win 8) from the menu, and the reading begins until it reaches about 3GB and then fails with the following error: "[-] Error: forensic1394_read_device_v: General I/O error"

Example of some runs below with Kali (all OS variations and inceptions versions give the same result):
=========================================================
root@kali:/opt/inception-0.4.0# ./incept unlock
...

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID):  (0x0)

[*] Only one device present, device auto-selected as target
[*] Selected device: MICROSOFT CORP.
[\] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[*] Available targets (known signatures):

[1] Windows 8 MsvpPasswordValidate unlock/privilege escalation
[2] Windows 7 MsvpPasswordValidate unlock/privilege escalation
[3] Windows Vista MsvpPasswordValidate unlock/privilege escalation
[4] Windows XP MsvpPasswordValidate unlock/privilege escalation
[5] Mac OS X DirectoryService/OpenDirectory unlock/privilege escalation
[6] Ubuntu libpam unlock/privilege escalation
[7] Linux Mint libpam unlock/privilege escalation
[8] Generic Linux Getty preauthenticated patch

[?] Please select target (or enter 'q' to quit): 1
[*] Selected target: Windows 8 MsvpPasswordValidate unlock/privilege escalation
[===========================================================================================================>                                        ] 2975 MiB ( 73%) {000000000000000000007570706f72742053656375}
[-] Error: forensic1394_read_device_v: General I/O error
=========================================================
=========================================================
root@kali:/opt/inception-0.3.5# ./incept unlock

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.3.5 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[!] Arguments unlock ignored
[*] FireWire devices on the bus (names may appear blank):
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID):  (0x0)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[*] Selected device: MICROSOFT CORP.
[*] Available targets (known signatures):
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1] Windows 8: msv1_0.dll MsvpPasswordValidate unlock/privilege escalation
[2] Windows 7: msv1_0.dll MsvpPasswordValidate unlock/privilege escalation
[3] Windows Vista: msv1_0.dll MsvpPasswordValidate unlock/privilege escalation
[4] Windows XP: msv1_0.dll MsvpPasswordValidate unlock/privilege escalation
[5] Mac OS X: DirectoryService/OpenDirectory unlock/privilege escalation
[6] Ubuntu: libpam unlock/privilege escalation
[7] Linux Mint: libpam unlock/privilege escalation
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[?] Please select target (or enter 'q' to quit): 2
[*] Selected target: Windows 7: msv1_0.dll MsvpPasswordValidate unlock/privilege escalation
[\] Initializing bus and enabling SBP-2, please wait  1 seconds or press Ctrl+C
[*] DMA shields should be down by now. Attacking...
[============================================================================================================================================>                                                    ] 2991 MiB ( 73%)
[!] I/O Error, make sure FireWire interfaces are properly connected
[!] Attack unsuccessful
=========================================================

II) Dump Issue: Also, if I try to do a dump on the same target (even if I reboot the victim and try again fresh) I get the audio indicator on a firewire device install on the victim and then inception fails immediately with this error:  "[-] Error: forensic1394_read_device_v: General I/O error"

==========================================================
root@kali:/opt/inception-0.4.0# ./incept dump
...

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[*] FireWire devices on the bus (names may appear blank):

[1] Vendor (ID): MICROSOFT CORP. (0x50f2) | Product (ID):  (0x0)

[*] Only one device present, device auto-selected as target
[*] Selected device: MICROSOFT CORP.
[\] Initializing bus and enabling SBP-2, please wait or press Ctrl+C
[*] Dumping from 0x0 to 0x100000000, a total of 4 GiB:
[-] Error: forensic1394_read_device_v: General I/O error
==========================================================

III) Test Issue: If I try a test function with inception, I get this output again across all variations of attacker, victims and versions:

=========================================================
root@kali:/opt/inception-0.4.1# ./incept test

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

.....E........
======================================================================
ERROR: test_unlock (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.2/unittest/case.py", line 370, in _executeTestPart
    function()
  File "/usr/lib/python3.2/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: test_unlock
Traceback (most recent call last):
  File "/usr/lib/python3.2/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.2/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/opt/inception-0.4.1/inception/test/test_unlock.py", line 31, in <module>
    from importlib.machinery import SourceFileLoader
ImportError: cannot import name SourceFileLoader


----------------------------------------------------------------------
Ran 14 tests in 0.162s

FAILED (errors=1)
[*] BRRRRRRRAAAAAWWWWRWRRRMRMRMMRMRMMMMM!!!
=========================================================

**Comment by carmaa** [comment]
The problems that you are having with reading memory around and over 3GiB is due to the limitations as detailed in mo post above. *This is not a bug in inception, but a limitation in FireWire*. Please read the above posted links.

Your 3rd issue is possibly an issue with accessing the low memory region of windows 7/8. I'm going to close this issue as not an issue, and create a separate issue for your issue no. 3.

**Comment by wintermute4316** [comment]
Hi carmaa.  Yes I read that in the post earlier about how a system could map have other devices producing gaps and that makes sense.  However Is it possible for the "dump" function to at least write out any memory it is able to read instead of failing right away?  I noticed with the unlock function, that it appears to read up to about the 3Gb mark but then bombs out, but with the dump function, it just fails immediately.  If it could write out whatever it's able to read, that would at least provide some portion of RAM which may contain something useful.
