### ISSUE TITLE
Does not work over thunderbolt

### ISSUE THREAD

**Issue by mossberg** [carmaa/inception#114]
I have two machines connected via thunderbolt, and when I run incept on the probing device (Linux), I get this error. Has incept been implemented for thunderbolt yet?

```
[-] Error: No module named 'inception.interfaces.thunderbolt'
```

**Comment by carmaa** [comment]
That's right, attacking over thunderbolt is really attacking over FireWire through a Thunderbolt wire. So when using Thunderbolt, just type

    incept unlock

or alternatively

    incept unlock -i firewire

I have in fact not tested the tool with thunderbolt to thunderbolt without any form of firewire to thunderbolt adapter (e.g., firewire on the attacking side, and thunderbolt on the victim. So let me know your mileage.

**Comment by mossberg** [comment]
It did not work at all for me with direct thunderbolt. The above error was from using the `-i thunderbolt` flag. I don't anticipate it working without firewire because libforensic1394 is firewire specific.

**Comment by carmaa** [comment]
Yep, I've clarified that in the README. Thanks for reporting!
