### ISSUE TITLE
undefined symbol: forensic1394_get_device_node_id

### ISSUE THREAD

**Issue by toutounek** [carmaa/inception#115]
Hi,

Just tried to run Inception on a fresh Kali install, but compatibility with libforensic seems not to work anymore.
Everytime I want to use a module using the firewire, I got "[!] Warning: Something went dreadfully wrong, full stack trace below: /usr/local/lib/libforensic1394.so.1: undefined symbol: forensic1394_get_device_node_id"

Is it a known bug?

Thanks you for the answer, and thank you for your amazing work.

root@kali-asa:~# incept unlock

 _|  _|      _|    _|_|_|  _|_|_|_|  _|_|_|    _|_|_|  _|    _|_|    _|      _|
 _|  _|_|    _|  _|        _|        _|    _|    _|    _|  _|    _|  _|_|    _|
 _|  _|  _|  _|  _|        _|_|_|    _|_|_|      _|    _|  _|    _|  _|  _|  _|
 _|  _|    _|_|  _|        _|        _|          _|    _|  _|    _|  _|    _|_|
 _|  _|      _|    _|_|_|  _|_|_|_|  _|          _|    _|    _|_|    _|      _|

v.0.4.0 (C) Carsten Maartmann-Moe 2015
Download: http://breaknenter.org/projects/inception | Twitter: @breaknenter

[!] Warning: Something went dreadfully wrong, full stack trace below: /usr/local/lib/libforensic1394.so.1: undefined symbol: forensic1394_get_device_node_id

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/EGG-INFO/scripts/incept", line 163, in main
    fromlist=['inception.interfaces'])
  File "/usr/local/lib/python3.2/dist-packages/inception-0.4.0-py3.2.egg/inception/interfaces/firewire.py", line 38, in <module>
    from forensic1394.bus import Bus
  File "/usr/local/lib/python3.2/dist-packages/forensic1394/__init__.py", line 1, in <module>
    from .bus import Bus
  File "/usr/local/lib/python3.2/dist-packages/forensic1394/bus.py", line 25, in <module>
    from forensic1394.functions import forensic1394_alloc, forensic1394_destroy, \
  File "/usr/local/lib/python3.2/dist-packages/forensic1394/functions.py", line 150, in <module>
    forensic1394_get_device_node_id = lib.forensic1394_get_device_node_id
  File "/usr/lib/python3.2/ctypes/__init__.py", line 366, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.2/ctypes/__init__.py", line 371, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libforensic1394.so.1: undefined symbol: forensic1394_get_device_node_id

**Comment by carmaa** [comment]
Thanks for reporting. Not able to reproduce this on a fresh Kali install.

Looks like the python modules may be unable to locate your libforensic1394 libs.

Can you try changing line 39 in `inception/interfaces/firewire.py` to:

    except (OSError, AttributeError):

and try to re-install & run the tool?

**Comment by toutounek** [comment]
Thank you, you found out what was not working.
After changing line 39 to "except (OSError, AttributeError):", the tool output was:
[-] Error: Could not load libforensic1394, please make sure libforensic1394 is in your PATH

So I just reinstalled forensic1394 (just in case), and ran "ldconfig" to reload the libraries.

Strange that Kali does not automatically load new libraries...

That worked like a charm :-)

**Comment by carmaa** [comment]
Great! I suspected it was something libforensic1394-related.
