### ISSUE TITLE
Why win 8.1 Unlock lock screen is Yes?

### ISSUE THREAD

**Issue by fghhfg** [carmaa/inception#116]
Why [cell](https://github.com/carmaa/inception#unlock) of Unlock lock screen is `Yes` in README.md?

In [Caveats paragraph](https://github.com/carmaa/inception#caveats), you say 
> OS X > 10.7.2 and Windows > 8.1 disables FireWire DMA when the user has locked the OS and thus prevents inception.

**Comment by carmaa** [comment]
If you read the *next sentence* in the caveats section it does say that the tool will still work when the user is logged on. This is relevant as the tool can attack over projector daisy chained over thunderbolt:

"OS X > 10.7.2 and Windows > 8.1 disables FireWire DMA when the user has locked the OS and thus prevents inception. The tool will still work while a user is logged on. However, this is a less probable attack scenario IRL."
