### ISSUE TITLE
Signature for Windows 10 Enterprise x64 (Version 1511 OS Build 10586.71)

### ISSUE THREAD

**Issue by galaris** [carmaa/inception#122]
Hello,

Here is the signature for win 10 x64 if anyone needs it:

- **offsets=0x14f**
- **chunk=0xc60f84**
- **chunkoffset=0x00**
- **patch=0xb001**
- **patchoffset=0x07**

It looks like Microsoft moved the msvpPasswordValidate function from the msv1_0.dll to NtlmShared.dll in Windows 10.

The following NtlmShared.dll was used to get the signature:

- 10.0.10586.0 (th2_release.151029-1700) 
- MD5:    62439C947C098FBAAAA0F50464F901A5
- SHA-1: 30979C7017426D0291F9A533D9CCF18F6B004DB8

The signature was validated, worked for me. I added a pull request too :)

**Comment by galaris** [comment]
#121

**Comment by galaris** [comment]
@carmaa #121

**Comment by carmaa** [comment]
Merged, thanks!
