### ISSUE TITLE
New unlock offset for Windows 7 SP1 x64 Enterprise (msv1_0.dll 6.1.7601.19160)

### ISSUE THREAD

**Issue by altf4** [carmaa/inception#124]
0xe19

^ That's the offset. I can confirm it works on my machines that run this version. I'd be happy to provide more info if needed.

**Comment by blunden** [comment]
To receive the proper credit you should submit a pull request.

**Comment by altf4** [comment]
I don't really care about credit. But if it's any trouble, I could put this into a pull request I guess. Does it need unit tests as well?

**Comment by blunden** [comment]
OK. If that would be preferable to you, I suppose I could add it to the pull request I have open already.

**Comment by blunden** [comment]
Well, let me know if you want me to include it in mine or if you want to submit your own pull request.

**Comment by altf4** [comment]
To be honest, I'm probably not going to have time to put together a pull request. :) Just go ahead and put it in yours.
