### ISSUE TITLE
Twitter @breaknenter dead?

### ISSUE THREAD

**Issue by schmiedecker** [carmaa/inception#134]
Not sure if the Twitter profile linked in the readme is still activ/valid? No clue what Salwar Suits are, but ...

![screenshot_2017-10-26_18-08-26](https://user-images.githubusercontent.com/16700221/32064009-f392a440-ba78-11e7-88a0-17eb0207b233.png)

**Comment by carmaa** [comment]
Yup - it's dead and presumably taken over by a squatter. Changing it.
