### ISSUE TITLE
any tool same as inception?

### ISSUE THREAD

**Issue by AJquetta** [carmaa/inception#139]
hello, if you can tell me if there is any tool that i can use to gather information from hardware interfaces? same like inception?

thanks.

**Comment by carmaa** [comment]
https://github.com/ufrisk/pcileech

**Comment by AJquetta** [comment]
i am getting an error that  unable to detect firewire ports while i have connected to the firewire port and everything is fine but it coming again and again. 

attack unlock 
attack unsuccessful 

can you help me how to solve this problem.
