### ISSUE TITLE
Segmentation fault: 11 on OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by digitalentropy** [carmaa/inception#85]
Installed Inception on my new late 2013 MacBook Pro today and ran into some issues.

After installing the dependencies via homebrew and then downloading and installing Inception, executing it results in an error that says "Python quit unexpectedly." and the terminal window reports "Segmentation fault: 11"

Host OS: Mac OS X 10.9 (13A3017)
Target OS: None (Running not connected to any targets to make sure app functions)

Beyond that it's a fresh factory OS image, with the exception of having FileVault 2 enabled.

**Comment by carmaa** [comment]
Closing this as VT-D issue. See README.md
